FROM node:25-alpine3.22

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi \
	&& npm cache clean --force

COPY --chown=node:node . .

RUN chown -R node:node /app

USER node

EXPOSE 8080

CMD ["npm", "run", "dev"]
